services:
  agenda-mysql:
    container_name: agenda-mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"  # Mapeo del puerto de MySQL

  agenda-app:
    container_name: agenda-app
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      - agenda-mysql
    ports:
      - "8200:8181"
    restart: unless-stopped